# -*- coding: utf-8 -*-
"""100 DAYS OF PYTHON_DAY 99_Space_Missions_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLEukRsibMOLZsenjhxsLI9IP8p7ZQaV

# Introduction

<center><img src="https://i.imgur.com/9hLRsjZ.jpg" height=400></center>

This dataset was scraped from [nextspaceflight.com](https://nextspaceflight.com/launches/past/?page=1) and includes all the space missions since the beginning of Space Race between the USA and the Soviet Union in 1957!

### Install Package with Country Codes
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install iso3166

"""### Upgrade Plotly

Run the cell below if you are working with Google Colab.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade plotly

"""### Import Statements"""

import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

# These might be helpful:
from iso3166 import countries
from datetime import datetime, timedelta

"""### Notebook Presentation"""

#set all float data to display only 2 decimal places
pd.options.display.float_format = '{:,.2f}'.format

"""### Load the Data"""

df_data = pd.read_csv('mission_launches.csv')

"""# Preliminary Data Exploration

* What is the shape of `df_data`?
* How many rows and columns does it have?
* What are the column names?
* Are there any NaN values or duplicates?
"""

#check the shape of the data. There are 4324 rows and 9 columns
df_data.shape

#View the first 5 rows of data and the column  names
df_data.head()

#view the last 5 rows of data
df_data.tail()

#View 5 random rows of data
df_data.sample(50)

"""## Data Cleaning - Check for Missing Values and Duplicates

Consider removing columns containing junk data.
"""

#check to see if the data contains any missing (nan) values
df_data.isna().values.any()

#check to see how many missing values the data contains
df_data.isna().values.sum()

#check to see if the data contains any duplicate rows
df_data.duplicated().values.any()

#view details about the data. See that Price is the only column with missing values
df_data.info()

#drop the Price column from the data frame since there are too many missing values
#also drop the two Unnamed columns, which are most likely index columns that were automatically generated
#or preserved during data export or manipulation
#print the first 5 rows of data to confirm that the Price column has been dropped
clean_df_data = df_data.drop(columns=['Price','Unnamed: 0.1', 'Unnamed: 0'], axis=1)
clean_df_data.head()

"""## Descriptive Statistics"""

#view descriptive statistics for cleaned df
clean_df_data.describe()

"""# Number of Launches per Company

Create a chart that shows the number of space mission launches by organisation.
"""

#save the count of space missions by organization to the variable org_launches
org_launches = clean_df_data.Organisation.value_counts().sort_values(ascending=False)
print(org_launches)

#create a horizontal graph that shows the number of space mission launches by Top 20 organizations.
plt.figure(dpi=200)
hor = px.bar(x=org_launches.values[:20],
             y=org_launches.index[:20],
             orientation='h',
             title='Number of Space Mission Launches by Top 20 Organizations')
hor.update_layout(xaxis_title='Number of Launches',
                  yaxis_title='Organization',
                  yaxis=dict(autorange='reversed'))
hor.show()

"""# Number of Active versus Retired Rockets

How many rockets are active compared to those that are decomissioned?
"""

rocket_status = clean_df_data['Rocket_Status'].value_counts()
rocket_status

"""# Distribution of Mission Status

How many missions were successful?
How many missions failed?
"""

mission_status = clean_df_data['Mission_Status'].value_counts()
mission_status

"""# How Expensive are the Launches?

Create a histogram and visualise the distribution. The price column is given in USD millions (careful of missing values).
"""

#remove commas and change data in the Price column from object type to numerical type
price = df_data['Price'].copy()
price = df_data['Price'].astype(str).str.replace(',', " ")
price = pd.to_numeric(df_data['Price'], errors='coerce')

#drop na values
price = price.dropna()

price.info()

#view the descritpive statistics for price
price.describe()

#create a histogram to visualize the price distribution for launching rockets
hist = px.histogram(price,
                    nbins=10,
                    title='Distribution of Rocket Launch Prices')
hist.update_layout(xaxis_title='Price in Millions', showlegend=False)
hist.show()

"""# Use a Choropleth Map to Show the Number of Launches by Country

* Create a choropleth map using [the plotly documentation](https://plotly.com/python/choropleth-maps/)
* Experiment with [plotly's available colours](https://plotly.com/python/builtin-colorscales/). I quite like the sequential colour `matter` on this map.
* You'll need to extract a `country` feature as well as change the country names that no longer exist.

Wrangle the Country Names

You'll need to use a 3 letter country code for each country. You might have to change some country names.

* Russia is the Russian Federation
* New Mexico should be USA
* Yellow Sea refers to China
* Shahrud Missile Test Site should be Iran
* Pacific Missile Range Facility should be USA
* Barents Sea should be Russian Federation
* Gran Canaria should be USA


You can use the iso3166 package to convert the country names to Alpha3 format.
"""

from iso3166 import countries_by_name

#custom mapping for renaming countries whose names no longer exist or changed
custom_map = {
    'Russia': 'Russian Federation',
    'New Mexico': 'USA',
    'Yellow Sea': 'China',
    'Shahrud Missile Test Site': 'Iran',
    'Pacific Missile Range Facility': 'USA',
    'Barents Sea': 'Russian Federation',
    'Gran Canaria': 'USA',

}

#Extract the country name from the Location column using inline lambda function and adding Country column to the dataframe
clean_df_data['Country'] = clean_df_data['Location'].apply(lambda x: x.split(",")[-1].strip())

#Apply custom mapping
clean_df_data['Country'] = clean_df_data['Country'].replace(custom_map)
clean_df_data

#Use iso3166 to convert country names to 3-letter codes and adding Country_Code to the dataframe.

def get_alpha3(name):
  try:
        return countries_by_name[name.upper()].alpha3
  except KeyError:
    if name == "USA":
        return "USA"
    else:
      return "UNKNOWN"

clean_df_data["Country_Code"] = clean_df_data["Country"].apply(get_alpha3)
clean_df_data

#get the count for the number of launches by country
num_launches = clean_df_data['Country_Code'].value_counts().reset_index()
num_launches.columns = ['Country_Code', 'Launch_Count']
num_launches

#create map that shows the number of rocket launches by country
launch_map = px.choropleth(num_launches,
                               locations='Country_Code',
                               color='Launch_Count',
                               color_continuous_scale='dense',
                               title="Rocket Launches by Country",
                               )
launch_map.update_layout(geo=dict(showframe=False, showcoastlines=True),
    margin=dict(l=0, r=0, t=50, b=0)
)


launch_map.show()

"""# Use a Choropleth Map to Show the Number of Failures by Country

"""

#create dataframe that contains only country data for all failed missions
num_failures = clean_df_data['Country_Code'][clean_df_data['Mission_Status'] != 'Success'].value_counts().reset_index()
num_failures.columns=['Country_Code', 'Failed_Missions']
num_failures

#create map to show number of failed missions by country
failure_map = px.choropleth(num_failures,
                               locations='Country_Code',
                               color='Failed_Missions',
                               color_continuous_scale='matter',
                               title="Failed Missions by Country",
                               )
failure_map.update_layout(geo=dict(showframe=False, showcoastlines=True),
    margin=dict(l=0, r=0, t=50, b=0)
)


failure_map.show()

"""# Create a Plotly Sunburst Chart of the countries, organisations, and mission status."""

#group data by Country, Organisation, and Mission Status and get the count for the Mission Status
launch_status = clean_df_data.groupby(['Country', 'Organisation', 'Mission_Status']).size().reset_index(name='Count')
print(launch_status[['Country', 'Organisation', 'Mission_Status']])

#create a sunburst chart theat shows the grouped data by Country, Organisation, and counts of Mission Status
mission_burst = px.sunburst(launch_status,
                  path=['Country', 'Organisation', 'Mission_Status'],
                  values='Count',
                  color='Country',
                  title='Mission Status by Country and Organization?')

mission_burst.update_layout(xaxis_title='Mission Status',
                    yaxis_title='Country',
                    coloraxis_showscale=False)

mission_burst.show()

"""# Analyse the Total Amount of Money Spent by Organisation on Space Missions"""

#create a new dataframe containing organization and price
price_df = df_data[['Organisation','Price']].copy()

#clean price column by removing comma and converting to numeric
price_df['Price'] = price_df['Price'].astype(str).str.replace(",", "")
price_df['Price'] = pd.to_numeric(price_df['Price'], errors='coerce')

# Drop rows where Price is NaN
price_df = price_df.dropna(subset=['Price'])

#get the total money spent by organization
money_spent = price_df.groupby(['Organisation'], as_index=False).agg({'Price':'sum'}).sort_values(by='Price', ascending=False)
money_spent

total_spent = px.bar(x=money_spent.Price[:20],
                     y=money_spent.Organisation[:20],
                     title='Total Amount of Money Spent by Organisation')
total_spent.update_layout(xaxis_title='Price in Millions',
                          yaxis_title='Organization',
                          yaxis=dict(autorange='reversed'))
total_spent.show()

"""# Analyse the Amount of Money Spent by Organisation per Launch"""

#create a new dataframe containing organization and price
price_launch_df = df_data[['Organisation','Price', 'Mission_Status']].copy()

#clean price column by removing comma and converting to numeric
price_launch_df['Price'] = price_launch_df['Price'].astype(str).str.replace(",", "")
price_launch_df['Price'] = pd.to_numeric(price_launch_df['Price'], errors='coerce')

# Drop rows where Price is NaN
price_launch_df = price_launch_df.dropna(subset=['Price'])

#get the total money spent and the total number of missions by organization
money_launch_spent = price_launch_df.groupby(['Organisation'], as_index=False).agg({'Price':'sum', 'Mission_Status': 'count'}).sort_values(by='Price', ascending=False)

money_launch_spent['Price_Per_Launch'] = money_launch_spent.Price/money_launch_spent.Mission_Status
money_launch_spent_sorted = money_launch_spent.sort_values(by='Price_Per_Launch', ascending=False)
money_launch_spent_sorted

price_per_launch = px.bar(x=money_launch_spent_sorted.Price_Per_Launch,
                          y=money_launch_spent_sorted.Organisation,
                          title=' Amount of Money Spent Per Launch',
                          color_discrete_sequence=['#2ecc71'])
price_per_launch.update_layout(xaxis_title='Price Per Launch',
                               yaxis_title='Organization',
                               yaxis=dict(autorange='reversed'))
price_per_launch.show()

"""# Chart the Number of Launches per Year"""

#create a new data frame date_df
date_df = clean_df_data.copy()

#remove UTC to standardize Date column
date_df['Date'] = date_df['Date'].astype(str).str.replace('UTC', '')

#Convert Date column from object to datetime format and view column info for confirmation
date_df['Date'] = pd.to_datetime(date_df['Date'], errors='coerce')
date_df['Date'].info()

#check fo NAN values post datetime conversion
date_df['Date'].isna().values.sum()

#check fo NAN values post datetime conversion
date_df['Date'].isna().value_counts()

#Tried different formatting of Date column to try to mitigate data being converted to NAN post datetime conversion.
#Since could not find any solution even after research, will drop rows with NAN values
date_df = date_df.dropna(subset=['Date'])

#abstract only the year from the Date column and create a new column "year"
date_df['Year'] = date_df['Date'].dt.year

#cheack for NAN values in the year column
date_df['Year'].isna().values.sum()

#print 30 random rows to check that the Date and Year column formatting was successful
date_df.sample(30)

#create a dataframe that contains the count of lauches per year
launch_per_year = date_df.groupby('Year').size().reset_index(name='Launches')
launch_per_year

#graph the number of launches per year
plt.figure(figsize=(8,6), dpi=200)

plt.xlabel('Date', fontsize=12)
plt.ylabel('Number of Launches', fontsize=12)
plt.title('Number of Launches Per Year', fontsize=14)

plt.plot(launch_per_year.Year, launch_per_year.Launches)
plt.show()

"""# Chart the Number of Launches Month-on-Month until the Present

Which month has seen the highest number of launches in all time? Superimpose a rolling average on the month on month time series chart.
"""

#create a new column for yearmonth data
date_df['YearMonth'] = date_df['Date'].dt.to_period('M')

#view data to confirm column was successfully added
date_df.head()

date_df['YearMonth'].info()

#Convert YearMonth to datetime object(e.g. timestamp representing the start of the month)
date_df['YearMonth'] = date_df['YearMonth'].dt.to_timestamp()

date_df['YearMonth'].info()

#cheack for NAN values in the monthyear column
date_df['YearMonth'].isna().values.sum()

#create a dataframe that contains the number of launches month to month
launch_month_to_month = date_df.groupby('YearMonth').size().reset_index(name='Launches')
launch_month_to_month = launch_month_to_month.sort_values('YearMonth')
launch_month_to_month

#Graph the Number of Launches Month-on-Month until the Present
plt.figure(figsize=(8,6), dpi=200)

plt.xlabel('Month-to-Month')
plt.ylabel('Number of Launches')
plt.title('Number of Launches Month-on-Month')

plt.plot(launch_month_to_month.YearMonth, launch_month_to_month.Launches)

plt.show()

#calculate the rolling mean for the number of launches month-to-month
rolling_month = launch_month_to_month['Launches'].rolling(window=6).mean()

#Graph the Number of Launches Month-on-Month until the Present and superimpose a rolling average on the month on month time series

plt.figure(figsize=(8,6), dpi=200)

plt.xlabel('Month-to-Month')
plt.ylabel('Number of Launches')
plt.title('Number of Launches Month-on-Month vs Rolling Average')

plt.plot(launch_month_to_month.YearMonth, launch_month_to_month.Launches, alpha=0.6)
plt.plot(launch_month_to_month.YearMonth, rolling_month, color='crimson')


plt.xticks(rotation=45)   # rotate labels for readability
plt.tight_layout()


plt.show()

"""# Launches per Month: Which months are most popular and least popular for launches?

Some months have better weather than others. Which time of year seems to be best for space missions?
"""

# Extract full month name directly from the Date column and create a new column "Month_Name"
date_df['Month_Name'] = date_df['Date'].dt.strftime('%B')

#check Month_Name column for NAN values
date_df['Month_Name'].isna().values.sum()

#print 30 random rows to check that the Month_Name column formatting was successful
date_df.sample(30)

#Get the count of launches for each month
month_counts = date_df['Month_Name'].value_counts()
month_counts

#Determine the most popular and the least popular month for launches
most_popular = month_counts.idxmax()
least_popular = month_counts.idxmin()
print(f"The most popular month for launches is {most_popular} ")
print(f"The least popular month for launches is {least_popular} ")

#Determine the top 3 most popular and the top 3 least popular months for launches
Top_3_most_popular = month_counts.head(3).index.to_list()
print(f"The Top_3_most_popular months for lauches are {Top_3_most_popular}")

Top_3_least_popular = month_counts.tail(3).index.to_list()
print(f"The Top_3_least_popular months for lauches are {Top_3_least_popular}")

"""# How has the Launch Price varied Over Time?

Create a line chart that shows the average price of rocket launches over time.
"""

#create a new dataframe containing date and price
price_change_df = df_data[['Date','Price']].copy()

#clean price column by removing comma and converting to numeric
price_change_df['Price'] = price_change_df['Price'].astype(str).str.replace(",", "")
price_change_df['Price'] = pd.to_numeric(price_change_df['Price'], errors='coerce')

# Drop rows where Price is NaN
price_change_df = price_change_df.dropna(subset=['Price'])

#remove UTC to standardize Date column
price_change_df['Date'] = price_change_df['Date'].astype(str).str.replace('UTC', '')

#covert Date column to datetime
price_change_df['Date'] = pd.to_datetime(price_change_df['Date'], errors='coerce')

#view column issue to confirm conversion
price_change_df['Date'].info()

#check for NAN values in Date column post conversion
price_change_df['Date'].isna().values.sum()

#check for NAN values in Date column post conversion
price_change_df['Date'].isna().value_counts()

#Tried different formatting of Date column to try to mitigate data being converted to NAN post datetime conversion.
#Since could not find any solution even after research, will drop rows with NAN values
price_change_df = price_change_df.dropna(subset=['Date'])

#abstract only the year from the Date column and create a new column "year"
price_change_df['Year'] = price_change_df['Date'].dt.year

#check for NAN values in the year column
price_change_df['Year'].isna().values.sum()

#print 30 random rows to confirm the year column was successfully added and formatted
price_change_df.sample(30)

#get the total price of launches per year
price_change_time = price_change_df.groupby(['Year'], as_index=False).agg({'Price':'mean'})
price_change_time

#graph to show how launch price varied over time
plt.figure(figsize=(8,6), dpi=200)

plt.xlabel('Date', fontsize=12)
plt.ylabel('Average Price in Millions', fontsize=12)
plt.title('Average Launch Price Over Time', fontsize=14)

plt.plot(price_change_time.Year, price_change_time.Price)
plt.show()

"""# Chart the Number of Launches over Time by the Top 10 Organisations.

How has the dominance of launches changed over time between the different players?
"""

#create a dataframe that contains the count of lauches over time by the top 10 organizations

#group data by organization and year
launch_count = date_df.groupby(['Organisation', 'Year']).size().reset_index(name='Launches')

#find the top ten organizations
top_ten_orgs = date_df['Organisation'].value_counts().nlargest(10).index

#filter data to include only the top ten organizations
launch_over_time = launch_count[launch_count['Organisation'].isin(top_ten_orgs)]

#view dataframe
launch_over_time

#graph to show how launch price varied over time
plt.figure(figsize=(8,6), dpi=200)

graph = px.line(launch_over_time,
                x='Year',
                y='Launches',
                color='Organisation',
                title='Number of Launches over Time by the Top 10 Organisations')

graph.show()

"""# Cold War Space Race: USA vs USSR

The cold war lasted from the start of the dataset up until 1991.
"""

#filter data to include data up to 1991
cold_war = date_df[date_df['Year']<= 1991]

#get launch count for the USA
usa_count = cold_war[cold_war['Country']=='USA'].shape[0]

#get launch count for the Russian Federation and Kazakhstan
ussr_count = cold_war[cold_war['Country'].isin(['Russian Federation', 'Kazakhstan'])].shape[0]

"""## Create a Plotly Pie Chart comparing the total number of launches of the USSR and the USA

Hint: Remember to include former Soviet Republics like Kazakhstan when analysing the total number of launches.
"""

#create a pie chart comparing the total number of launches of the USSR and the USA
pie_chart = px.pie(labels=['USA', 'USSR'], values=[usa_count, ussr_count], title='Cold War Space Race: USA vs USSR', names=['USA', 'USSR'])

pie_chart.show()

"""## Create a Chart that Shows the Total Number of Launches Year-On-Year by the Two Superpowers"""

# Create a new column that merges RUS and KAZ into a single group
cold_war['Country_Group'] = cold_war['Country_Code'].replace({'RUS': 'USSR', 'KAZ': 'USSR'})

# Group by Year and the new Country_Group column. "unstack" reshapes the data for plotting by pivoting the inner index level (Country_Group) into columns.
#"fill_value=0" replaces all missing values with 0, since not every year has launches from every country.
launch_counts = cold_war.groupby(['Year', 'Country_Group']).size().unstack(fill_value=0)


#ploy graph using matplotlib
ax = launch_counts[['USSR', 'USA']].plot(kind='line', figsize=(10, 6))

ax.set_ylabel("Number of Launches")
ax.set_title("USA vs USSR Launches by Year")

plt.show()

"""## Chart the Total Number of Mission Failures Year on Year."""

#filter data to include only failed missions
mission_failures = cold_war[cold_war['Mission_Status']=="Failure"]

#group failures by year and country
failures_per_year = mission_failures.groupby(['Year', 'Country_Group']).size().unstack(fill_value=0)

#plot graph
ax = failures_per_year[['USSR', 'USA']].plot(kind='line', figsize=(10, 6))

ax.set_ylabel('Mission Failures')
ax.set_title('USA vs USSR Mission Failures Per Year')

plt.show()

"""## Chart the Percentage of Failures over Time

Did failures go up or down over time? Did the countries get better at minimising risk and improving their chances of success over time?
"""

#calculate the percentage of failures
failure_pct = (failures_per_year / launch_counts) * 100

#plot the graph
ax = failure_pct[['USA', 'USSR']].plot(kind='line', figsize=(10,6))

ax.set_ylabel('Percentage of Failures')
ax.set_title('USA vs USSR Percentage of Mission Failures Over Time')

plt.show()

"""# For Every Year Show which Country was in the Lead in terms of Total Number of Launches up to and including including 2020)

Do the results change if we only look at the number of successful launches?
"""

# Create a new column that merges RUS and KAZ into a single group
date_df['Country_Group'] = date_df['Country_Code'].replace({'RUS': 'USSR', 'KAZ': 'USSR'})

# Group by Year and the new Country_Group column. "unstack" reshapes the data for plotting by pivoting the inner index level (Country_Group) into columns.
#"fill_value=0" replaces all missing values with 0, since not every year has launches from every country.
total_launch_counts = date_df.groupby(['Year', 'Country_Group']).size().unstack(fill_value=0)

#determine which country led each year
leader_by_year = total_launch_counts[['USA', 'USSR']].idxmax(axis=1)


# Convert country names to numeric codes for plotting
leader_numeric = leader_by_year.replace({'USA': 1, 'USSR': 2})

# Plot the numeric leader values
ax = leader_numeric.plot(kind='line', figsize=(10, 6))
ax.set_yticks([1, 2])
ax.set_yticklabels(['USA', 'USSR'])
ax.set_ylabel('Launch Leader')
ax.set_title('Yearly Launch Leader: USA vs USSR')

plt.show()

#look at only successful launches
successful_missions = date_df[date_df['Mission_Status']=='Success']

# Group by Year and the new Country_Group column. "unstack" reshapes the data for plotting by pivoting the inner index level (Country_Group) into columns.
#"fill_value=0" replaces all missing values with 0, since not every year has launches from every country.
total_launch_counts = successful_missions.groupby(['Year', 'Country_Group']).size().unstack(fill_value=0)

#determine which country led each year
leader_by_year = total_launch_counts[['USA', 'USSR']].idxmax(axis=1)


# Convert country names to numeric codes for plotting
leader_numeric = leader_by_year.replace({'USA': 1, 'USSR': 2})

# Plot the numeric leader values
ax = leader_numeric.plot(kind='line', figsize=(10, 6))
ax.set_yticks([1, 2])
ax.set_yticklabels(['USA', 'USSR'])
ax.set_ylabel('Launch Leader')
ax.set_title('Yearly Launch Leader: USA vs USSR')

plt.show()

"""# Create a Year-on-Year Chart Showing the Organisation Doing the Most Number of Launches

Which organisation was dominant in the 1970s and 1980s? Which organisation was dominant in 2018, 2019 and 2020?
"""

#get launch count by organization
total_launches = date_df.groupby(['Year', 'Organisation']).size().unstack(fill_value=0)

#get the leading organization
leader_org_by_year = total_launches.idxmax(axis=1)

#Convert organisation names to numeric codes for plotting
org_codes = {org: i for i, org in enumerate(leader_org_by_year.unique(), start=1)}
leader_numeric = leader_org_by_year.replace(org_codes)


#plot the graph
ax = leader_numeric.plot(kind='line', figsize=(12, 6))

ax.set_yticks(list(org_codes.values()))
ax.set_yticklabels(list(org_codes.keys()))

ax.set_ylabel("Organisation Leading Launch Count")
ax.set_xlabel("Year")
ax.set_title("Year-on-Year Launch Leader by Organisation")

plt.grid(True)
plt.tight_layout()
plt.show()